services:
    # DEV ----------------------------------------------------------------------
    proxy:
        profiles: ["dev"]
        build: ./proxy
        env_file:
            - ./backend/.env
            - ./frontend/.env
        networks:
            - task_manager
        ports:
            - '80:80'
    backend-dev:
        profiles: ["dev"]
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
            target: dev
        env_file:
            - ./backend/.env
        volumes:
            - ./backend/src:/backend/src
        networks:
            task_manager:
                aliases:
                    - backend
    frontend-dev:
        profiles: ["dev"]
        build:
            context: ./frontend/
            dockerfile: ./Dockerfile
            target: dev
        env_file:
            - ./frontend/.env
        volumes:
            - ./frontend/src:/frontend/src
        networks:
            task_manager:
                aliases:
                    - frontend
    # TEST ---------------------------------------------------------------------
    frontend-test:
        profiles: ["test"]
        build:
            context: ./frontend/
            dockerfile: ./Dockerfile
            target: test-unit
        env_file:
            - ./frontend/.env
        volumes:
            - ./frontend/src:/frontend/src
        networks:
            task_manager:
                aliases:
                    - frontend
networks:
    task_manager:
        driver: bridge
